import type { ShihuoLeasedSession, ShihuoProductLink, ShihuoProductLinkRepository, ShihuoResolutionStatus, ShihuoSessionRepository } from "../../../shihuo/index.js";
import type { SqlExecutor } from "../sql-executor.js";
import type { DatabaseRow } from "./row-mappers.js";
import { requireRow } from "./repository-utils.js";

const stamp = (value: unknown): string | null => value == null ? null : value instanceof Date ? value.toISOString() : String(value);
function link(row: DatabaseRow): ShihuoProductLink { return { sourceProductId: String(row.source_product_id), sourceArticle: String(row.source_article), normalizedArticle: String(row.normalized_article), goodsId: row.goods_id == null ? null : String(row.goods_id), styleId: row.style_id == null ? null : String(row.style_id), status: row.status as ShihuoResolutionStatus, confirmedArticle: row.confirmed_article == null ? null : String(row.confirmed_article), confirmedAt: stamp(row.confirmed_at), lastCardLoadedAt: stamp(row.last_card_loaded_at), lastErrorCode: row.last_error_code == null ? null : String(row.last_error_code) }; }

export class PostgresShihuoSessionRepository implements ShihuoSessionRepository {
  constructor(private readonly executor: SqlExecutor) {}
  async acquire(owner: string, leaseSeconds: number): Promise<ShihuoLeasedSession | null> {
    const result = await this.executor.query<DatabaseRow>(`WITH candidate AS (
      SELECT id FROM shihuo_guest_devices WHERE status='ready' AND guest_profile_ciphertext IS NOT NULL
        AND next_available_at <= NOW() AND (leased_until IS NULL OR leased_until <= NOW())
      ORDER BY last_used_at NULLS FIRST, id FOR UPDATE SKIP LOCKED LIMIT 1
    ) UPDATE shihuo_guest_devices device SET lease_owner=$1, leased_until=NOW()+($2::INTEGER*INTERVAL '1 second'), updated_at=NOW()
      FROM candidate WHERE device.id=candidate.id RETURNING device.id, device.guest_profile_ciphertext`, [owner, leaseSeconds]);
    const row = result.rows[0]; return row ? { deviceId: String(row.id), leaseOwner: owner, profileCiphertext: String(row.guest_profile_ciphertext) } : null;
  }
  async releaseSuccess(deviceId: string, owner: string, nextAvailableAt: string): Promise<void> { await this.executor.query(`UPDATE shihuo_guest_devices SET lease_owner=NULL,leased_until=NULL,last_used_at=NOW(),next_available_at=$3::timestamptz,consecutive_errors=0,cooldown_reason=NULL,updated_at=NOW() WHERE id=$1 AND lease_owner=$2`, [deviceId, owner, nextAvailableAt]); }
  async releaseFailure(deviceId: string, owner: string, nextAvailableAt: string, reason: string, pause: boolean): Promise<void> { await this.executor.query(`UPDATE shihuo_guest_devices SET lease_owner=NULL,leased_until=NULL,last_used_at=NOW(),next_available_at=$3::timestamptz,consecutive_errors=consecutive_errors+1,cooldown_reason=$4,status=CASE WHEN $5 THEN 'paused' ELSE status END,diagnostic_stage=CASE WHEN $5 THEN 'paused' ELSE diagnostic_stage END,updated_at=NOW() WHERE id=$1 AND lease_owner=$2`, [deviceId, owner, nextAvailableAt, reason, pause]); }
}

export class PostgresShihuoProductLinkRepository implements ShihuoProductLinkRepository {
  constructor(private readonly executor: SqlExecutor) {}
  async get(sourceProductId: string): Promise<ShihuoProductLink | null> { const result = await this.executor.query<DatabaseRow>("SELECT * FROM shihuo_product_links WHERE source_product_id=$1", [sourceProductId]); return result.rows[0] ? link(result.rows[0]) : null; }
  async savePending(sourceProductId: string, article: string, normalizedArticle: string): Promise<ShihuoProductLink> { const result = await this.executor.query<DatabaseRow>(`INSERT INTO shihuo_product_links(source_product_id,source_article,normalized_article,status) VALUES($1,$2,$3,'pending') ON CONFLICT(source_product_id) DO UPDATE SET source_article=EXCLUDED.source_article,normalized_article=EXCLUDED.normalized_article,status=CASE WHEN shihuo_product_links.status='resolved' AND shihuo_product_links.normalized_article=EXCLUDED.normalized_article THEN 'resolved' ELSE 'pending' END,goods_id=CASE WHEN shihuo_product_links.status='resolved' AND shihuo_product_links.normalized_article=EXCLUDED.normalized_article THEN shihuo_product_links.goods_id ELSE NULL END,style_id=CASE WHEN shihuo_product_links.status='resolved' AND shihuo_product_links.normalized_article=EXCLUDED.normalized_article THEN shihuo_product_links.style_id ELSE NULL END,confirmation_method=CASE WHEN shihuo_product_links.status='resolved' AND shihuo_product_links.normalized_article=EXCLUDED.normalized_article THEN shihuo_product_links.confirmation_method ELSE NULL END,confirmed_article=CASE WHEN shihuo_product_links.status='resolved' AND shihuo_product_links.normalized_article=EXCLUDED.normalized_article THEN shihuo_product_links.confirmed_article ELSE NULL END,confirmed_at=CASE WHEN shihuo_product_links.status='resolved' AND shihuo_product_links.normalized_article=EXCLUDED.normalized_article THEN shihuo_product_links.confirmed_at ELSE NULL END,last_error_code=NULL,updated_at=NOW() RETURNING *`, [sourceProductId, article, normalizedArticle]); return link(requireRow(result.rows,"Shihuo product link",sourceProductId)); }
  async saveResolved(input: Parameters<ShihuoProductLinkRepository["saveResolved"]>[0]): Promise<ShihuoProductLink> { const result = await this.executor.query<DatabaseRow>(`INSERT INTO shihuo_product_links(source_product_id,source_article,normalized_article,goods_id,style_id,status,confirmation_method,confirmed_article,confirmed_at,last_card_loaded_at) VALUES($1,$2,$3,$4,$5,'resolved','exact_article',$6,$7,$7) ON CONFLICT(source_product_id) DO UPDATE SET source_article=EXCLUDED.source_article,normalized_article=EXCLUDED.normalized_article,goods_id=EXCLUDED.goods_id,style_id=EXCLUDED.style_id,status='resolved',confirmation_method='exact_article',confirmed_article=EXCLUDED.confirmed_article,confirmed_at=EXCLUDED.confirmed_at,last_card_loaded_at=EXCLUDED.last_card_loaded_at,last_error_code=NULL,updated_at=NOW() RETURNING *`, [input.sourceProductId,input.article,input.normalizedArticle,input.goodsId,input.styleId,input.confirmedArticle,input.loadedAt]); return link(requireRow(result.rows,"Shihuo product link",input.sourceProductId)); }
  async saveOutcome(sourceProductId: string, status: Exclude<ShihuoResolutionStatus,"pending"|"resolved">, errorCode: string | null): Promise<ShihuoProductLink> { const result = await this.executor.query<DatabaseRow>(`UPDATE shihuo_product_links SET status=$2,goods_id=NULL,style_id=NULL,confirmation_method=NULL,confirmed_article=NULL,confirmed_at=NULL,last_error_code=$3,updated_at=NOW() WHERE source_product_id=$1 RETURNING *`, [sourceProductId,status,errorCode]); return link(requireRow(result.rows,"Shihuo product link",sourceProductId)); }
  async touchCard(sourceProductId: string, loadedAt: string): Promise<void> { await this.executor.query("UPDATE shihuo_product_links SET last_card_loaded_at=$2::timestamptz,last_error_code=NULL,updated_at=NOW() WHERE source_product_id=$1 AND status='resolved'", [sourceProductId,loadedAt]); }
}
