import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import type { SqlPool } from "../../src/infrastructure/db/sql-executor.js";
import { PostgresContentEnrichmentRepository } from "../../src/infrastructure/db/repositories/postgres-content-enrichment-repository.js";
import { validProduct } from "../support/in-memory.js";

const modulePath = process.env.CONTENT_QUERY_PGLITE_MODULE;
if (!modulePath) throw new Error("CONTENT_QUERY_PGLITE_MODULE is required");
const { PGlite } = await import(pathToFileURL(modulePath).href);
const db = new PGlite();
try {
  await db.exec(`CREATE TABLE source_products(id BIGINT PRIMARY KEY);
    CREATE TABLE internal_products(id BIGINT PRIMARY KEY,source_product_id BIGINT,data JSONB,content_hash TEXT,updated_at TIMESTAMPTZ);
    CREATE TABLE jobs(id BIGSERIAL PRIMARY KEY,job_type TEXT CONSTRAINT jobs_job_type_check CHECK(job_type IN('process_product')),
      payload JSONB,status TEXT,unique_key TEXT);
    CREATE UNIQUE INDEX jobs_active_unique_key_idx ON jobs(job_type,unique_key) WHERE status IN('pending','running','retry');
    INSERT INTO source_products VALUES(2);
    INSERT INTO internal_products VALUES(1,2,'{}','before',NOW());`);
  await db.exec(await readFile(new URL("../../src/infrastructure/db/migrations/105_product_content_enrichments.sql",import.meta.url),"utf8"));
  const pool: SqlPool = { connect: async () => ({ query: (q,values) => db.query(q,values),release() {} }),async end() {} };
  const repo = new PostgresContentEnrichmentRepository(pool);
  const input = { sourceProductId: "2",donorCode: "shihuo",donorProductKey: "1:2",article: "SKU",sourceLocale: "zh-CN",targetLocale: "ru",
    parserVersion: "1",rawPayload: {},cleanedText: "特性",status: "collected" as const,reason: null };
  const record = await repo.save(input);
  await repo.save(input);
  assert.equal((await db.query("SELECT COUNT(*)::int AS n FROM jobs")).rows[0].n,1);
  assert.equal(await repo.apply({ enrichmentId: record.id,internalProductId: "1",expectedContentHash: "wrong",data: validProduct(),contentHash: "after",translatedText: "Описание" }),false);
  assert.equal((await repo.get(record.id))?.status,"collected");
  assert.equal(await repo.apply({ enrichmentId: record.id,internalProductId: "1",expectedContentHash: "before",data: validProduct(),contentHash: "after",translatedText: "Описание" }),true);
  assert.equal((await repo.latestApplied("2"))?.translatedText,"Описание");
  assert.equal((await db.query("SELECT COUNT(*)::int AS n FROM jobs WHERE job_type='retranslate_product' AND payload->>'reclassifyAfter'='true'")).rows[0].n,1);
  await repo.skip(record.id,"race");
  assert.equal((await repo.get(record.id))?.status,"applied");
  assert.equal((await repo.save({ ...input,cleanedText: "changed" })).cleanedText,input.cleanedText);
  assert.equal(await repo.apply({ enrichmentId: record.id,internalProductId: "1",expectedContentHash: "after",data: validProduct(),contentHash: "unwanted",translatedText: "Повтор" }),false);
  assert.equal((await db.query("SELECT content_hash FROM internal_products WHERE id=1")).rows[0].content_hash,"after");
  await db.exec(`CREATE TABLE shihuo_product_links(source_product_id BIGINT,status TEXT,goods_id TEXT,style_id TEXT);
    CREATE TABLE rules_v2_workbench_items(source_product_id BIGINT,source_id BIGINT,target_id BIGINT,title TEXT,issue_count INT,issue_codes TEXT[]);
    CREATE TABLE target_products(internal_product_id BIGINT,target_id BIGINT);
    CREATE TABLE wordpress_catalog_runs(id BIGINT,target_id BIGINT);
    CREATE TABLE wordpress_catalog_run_items(run_id BIGINT,source_product_id BIGINT,match_status TEXT);
    CREATE TABLE target_product_preflight_reviews(target_id BIGINT,internal_product_id BIGINT,will_create BOOLEAN,external_id TEXT);
    INSERT INTO shihuo_product_links VALUES(2,'resolved','1','2');
    INSERT INTO rules_v2_workbench_items VALUES(2,1,1,'Product',1,ARRAY['description_missing']);
    UPDATE internal_products SET data='{"description":"","attributes":{}}';
    DELETE FROM product_content_enrichments;`);
  const cli = await readFile(new URL("../../src/cli/shihuo-descriptions.ts",import.meta.url),"utf8");
  const candidateQuery = /client\.query\(`(WITH links[\s\S]*?)`,/u.exec(cli)?.[1];
  assert.ok(candidateQuery);
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"0",true])).rows[0].candidates.length,1);
  await db.exec("INSERT INTO jobs(job_type,payload,status,unique_key) VALUES('collect_product_content','{\"sourceProductId\":\"2\"}','pending','source-product:2:content:shihuo')");
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"0",true])).rows[0].candidates.length,0);
  await db.exec("DELETE FROM jobs WHERE job_type='collect_product_content'");
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"2",true])).rows[0].cursor,null);
  await db.exec("INSERT INTO wordpress_catalog_runs VALUES(4,1); INSERT INTO wordpress_catalog_run_items VALUES(4,2,'matched')");
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"0",true])).rows[0].candidates.length,0);
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"0",false])).rows[0].candidates.length,1);
  await db.exec("DELETE FROM wordpress_catalog_run_items; INSERT INTO target_product_preflight_reviews VALUES(1,1,FALSE,'101')");
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"0",true])).rows[0].candidates.length,0);
  await db.exec("INSERT INTO target_products VALUES(1,1)");
  assert.equal((await db.query(candidateQuery,[1,1,3,null,"0",true])).rows[0].candidates.length,0);
  console.info(JSON.stringify({ passed: true,migration: true,atomicJobs: true,cas: true,replayRollback: true,appliedPreserved: true }));
} finally { await db.close(); }
